#!/usr/bin/bash
abc () {
  echo ABC Function
}
abc

#Declare Another function

function xyz()
{
  echo XYZ Function
}
xyz
#This is Function
Zeeshan ()
{
  echo a =$a
  echo b =$b

}
#Main Program
a=10
b=20

Zeeshan
