#!/usr/bin/bash
abc () {
  echo ABC Function
}
abc

#Declare Another function

function xyz()
{
  echo XYZ Function
}

#This is Function
Zeeshan ()
{
  echo a =$a
  b=20
}
#Main Program
a=10
echo b = $b

Zeeshan
